name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      BUCKET_NAME: aop-pagina-ia
      DYNAMO_TABLE_NAME: terraform-lock-table
      TFSTATE_KEY: terraform/terraform.tfstate

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Delete all objects in S3 bucket
        run: |
          echo "🧹 Borrando objetos del bucket..."
          aws s3 rm s3://$BUCKET_NAME --recursive || true

      - name: Delete Terraform state file from S3
        run: |
          echo "🧨 Borrando archivo terraform.tfstate del bucket..."
          aws s3 rm s3://$BUCKET_NAME/$TFSTATE_KEY || true

      - name: Delete lock from DynamoDB
        run: |
          echo "🔓 Borrando LockID de DynamoDB..."
          aws dynamodb delete-item \
            --table-name $DYNAMO_TABLE_NAME \
            --key "{\"LockID\": {\"S\": \"$TFSTATE_KEY\"}}" || true

      - name: Terraform Init (re-init clean)
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve
