name: Destruir Infraestructura con Terraform

on:
  workflow_dispatch:

jobs:
  destruir:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      BUCKET_NAME: aop-pagina-ia
      STATE_KEY: terraform/terraform.tfstate
      LOCK_ID: terraform/terraform.tfstate
      DYNAMODB_TABLE: terraform-lock-table

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Eliminar archivos del bucket S3
        run: |
          echo "🧹 Eliminando archivos del bucket: $BUCKET_NAME"
          aws s3 rm s3://$BUCKET_NAME --recursive || true

      - name: Eliminar archivo de estado remoto (S3)
        run: |
          echo "🧨 Eliminando estado remoto: $STATE_KEY"
          aws s3 rm s3://$BUCKET_NAME/${STATE_KEY} || true

      - name: Limpiar checksum (Digest) en DynamoDB
        run: |
          echo "🔧 Eliminando atributo Digest de DynamoDB..."
          aws dynamodb update-item \
            --table-name $DYNAMODB_TABLE \
            --key "{\"LockID\": {\"S\": \"${LOCK_ID}\"}}" \
            --update-expression "REMOVE Digest" || true

      - name: Inicializar Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Ejecutar Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve -lock=false
