name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform  # Mantén esto como está, para usar el directorio terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0  # (Opcional) Puedes especificar la versión de Terraform

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Download tfstate artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-state  # Asegúrate de que este nombre coincida con el nombre del artefacto subido
          path: terraform/       # Aquí corregimos la ruta para que coincida con la ubicación de terraform.tfstate

      - name: Verify terraform.tfstate file
        run: |
          echo "Verificando si terraform.tfstate existe"
          ls -l terraform/terraform.tfstate  # Verificar que el archivo se descargó correctamente

      - name: Terraform init
        run: terraform init

      - name: Terraform destroy
        run: terraform destroy -auto-approve
